import 'package:versity_project_coffee/database/coffeeModel.dart';

class CoffeeData {
  List<CoffeeModel> coffeeList = [
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 2,
      title: "Coffee 2",
      subTitle: "Cafe Milano",
      catagory: "Expresso",
      description: "description",
      image: "images/coffee1.jpg",
      price: "5.00",
      rating: "4.4",
      isfavorite: false,
      isRecommended: true,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 3,
      title: "Coffee 1",
      subTitle: "Monte Beans",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee2.jpeg",
      price: "4.99",
      rating: "4.0",
      isfavorite: true,
      isRecommended: false,
      isPurchased: true,
      purchaseDate: DateTime.utc(2022, 3, 9),
    ),
    CoffeeModel(
      id: 4,
      title: "Coffee 4",
      subTitle: "Arabica Mocha",
      catagory: "Machiato",
      description: "description 1",
      image: "images/coffee3.jpeg",
      price: "6.20",
      rating: "2.4",
      isfavorite: false,
      isRecommended: true,
      isPurchased: false,
    ),
    CoffeeModel(
        id: 5,
        title: "Coffee 5",
        subTitle: "Brew Cafe",
        catagory: "Latte",
        description: "description 1",
      image: "images/coffee4.jpeg",
        price: "2.20",
        rating: "4.4",
        isfavorite: false,
        isRecommended: true,
        isPurchased: true,
        purchaseDate: DateTime.utc(2021, 11, 2)),
    CoffeeModel(
      id: 6,
      title: "Coffee 6",
      subTitle: "Entertainment Java",
      catagory: "Mocha",
      description: "description 1",
      image: "images/coffee5.jpeg",
      price: "1.20",
      rating: "3.9",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 7,
      title: "Coffee 7",
      subTitle: "Sigma Brew",
      catagory: "Latte",
      description: "description 1",
      image: "images/coffee6.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: true,
      isRecommended: true,
      isPurchased: true,
      purchaseDate: DateTime.utc(2022),
    ),
    CoffeeModel(
      id: 8,
      title: "Coffee 8",
      subTitle: "Sigma Brew",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee7.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee8.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee1.jpg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee2.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee3.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee4.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee5.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee6.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee7.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee8.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee1.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
    CoffeeModel(
      id: 1,
      title: "Coffee 1",
      subTitle: "Brew Cafe",
      catagory: "Cuppuchino",
      description: "description 1",
      image: "images/coffee2.jpeg",
      price: "4.20",
      rating: "3.4",
      isfavorite: false,
      isRecommended: false,
      isPurchased: false,
    ),
  ];
  
  List<String> get catagoryList {
    List<String> uniCatagoryList = [];
    coffeeList.forEach((coffee) {
      if(!uniCatagoryList.contains(coffee.catagory)) uniCatagoryList.add(coffee.catagory); 
    });

    return uniCatagoryList;
  }
}
