name: versity_project_coffee
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adobe_xd: ^2.0.1
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^0.8.5+3
  lottie: ^1.4.0
  path_provider: ^2.0.10
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - asset/
    - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
