name: versity_project_coffee
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adobe_xd: ^2.0.1
  animated_splash_screen: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.20
  firebase: ^9.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  get: ^4.6.1
  google_fonts: ^2.3.1
  iconsax: ^0.0.8
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.15



dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

